image: registry.sindria.org/devops/base-images/image-builder:latest

stages:
  - build
  - push

before_script:
  - export BLUE='\033[0;34m'
  - export YELLOW='\033[0;33m'
  - export RED='\033[0;31m'
  - export NC='\033[0m' #No Color
  - export NOW=$(date "+%Y-%m-%d_%H-%M-%S")

build:image:
  stage: build
  tags:
    - docker
  only:
    - tags
  script:
    - echo -e "${BLUE}Building image...${NC}"
    - bash build.sh 1000 $CI_COMMIT_TAG registry.sindria.org/security/kali
    - cowsay -f tux "Build Success"

push:image:
  stage: push
  tags:
    - docker
  only:
    - tags
  script:
    - echo -e "${BLUE}Pushing image into registry...${NC}"
    - docker push registry.sindria.org/security/kali:$CI_COMMIT_TAG
    - docker push registry.sindria.org/security/kali:latest
    - echo #
    - echo -e "${BLUE}Cleaning local registry...${NC}"
    - docker image rm registry.sindria.org/security/kali:$CI_COMMIT_TAG
    - docker image rm registry.sindria.org/security/kali:latest
    - echo #
    - cowsay -f dragon "Well Done! New docker image is now on your registry."